### ISSUE TITLE
No testing on Windows has been done

### ISSUE THREAD

**Issue by Chris-Dobbins** [Chris-Dobbins/listdupes#21]
We're looking for Windows testers. It'd be nice to have some idea of if the code actually runs on Windows before releasing v6.0.0. Depending on the scope of any issues full Windows functionality might have to be a v6.1.0 or later goal, but it would be nice to address any show-stopping bugs in the v6 Beta period.

**Comment by geblerj** [comment]
Hey, your project sounds interesting, I'm more than willing to help out! What do you need me to do?

**Comment by Chris-Dobbins** [comment]
@geblerj Hey there, thanks for your interest! So I'm a life-long Mac and Unix user over here, no experience with Windows, but since Python is cross-platform I'd like to see what I can do to support recent versions of Windows. As I've been writing the code I've been trying to avoid the Unix-only features of the Python standard library, but I don't have any way to test whether I've been successful at that.

Right now I'm looking for basic feedback on if the program works on the Windows version of Python 3.9 or higher, and details on what you did to get it to run.

**Comment by geblerj** [comment]
@Chris-Dobbins ok yeah sounds good. Is there anything you’d like me to test specifically? (Also, this is my first time contributing to open-source, so apologies if I’m not entirely sure how to do things)

**Comment by geblerj** [comment]
@Chris-Dobbins yep it worked, printed out the help message

**Comment by geblerj** [comment]
@Chris-Dobbins I also just went ahead and tried running the script with a folder to search and it looks like it worked. It wrote the results to a csv file and had the logs as well.

**Comment by Chris-Dobbins** [comment]
@geblerj Wonderful! Thanks for moving ahead and doing some more testing, great to hear that it works. Now that we know it runs can you give me some info on the system you used for the test? Like:

- What version of Windows did you test it on?
- What version of Python did you use?
- If you installed that version of Python yourself do you remember where you got it? Microsoft Store? Python.org?
- And any information you can give me about what command-line you used. Seems like there are a few different options on Windows like PowerShell, and Windows Subsystem for Linux.
- What were the hardware specs like? What sort of processor? how much RAM?

**Comment by geblerj** [comment]
@Chris-Dobbins

**System info:**
- Windows 11 Pro (specifically, version 21H2, OS build 22000.795)
- Python 3.9.12
- I got it from python.org
- I am using Command Prompt
- Processor Type: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz; 16 GB of RAM


Also, you should know that it appears that the program doesn't like empty files. I was running it and kept on getting this Traceback:

`Traceback (most recent call last):`
`  File "C:\Users\jgebler\Downloads\listdupes-6.0.0-beta.3\listdupes.py", line 1266, in <module>`
`    main_result = main()`
`  File "C:\Users\jgebler\Downloads\listdupes-6.0.0-beta.3\listdupes.py", line 1230, in main`
`    search_result = search_for_dupes(checksum_input_values, show_progress=args.progress)`
`  File "C:\Users\jgebler\Downloads\listdupes-6.0.0-beta.3\listdupes.py", line 1076, in search_for_dupes`
`    checksum_result = checksum_files(`
`  File "C:\Users\jgebler\Downloads\listdupes-6.0.0-beta.3\listdupes.py", line 947, in checksum_files`
`    _checksum_file_and_store_outcome(file_path, paths_and_sums, os_errors)`
`  File "C:\Users\jgebler\Downloads\listdupes-6.0.0-beta.3\listdupes.py", line 839, in _checksum_file_and_store_outcome`
`    checksum = checksummer(chunk_generator.__next__(), 0)`
`StopIteration`

And I figured out that the reason is because of empty files. You can reproduce it by creating an empty file (it has to be 0 bytes; you can just create an empty test file) and then searching for duplicates in that directory, and you'll probably get the same error.

Also, I noticed that, when listdupes.py searches for duplicates, when it encounters a nested folder, it considers that a file it is unable to read. It isn't a huge issue, but I just wanted to make sure you knew about it. It could be confusing to others. (To reproduce, create an empty directory (f2) within an empty directory (f1) and run listdupes.py on it (f1, the one that only contains an empty directory). It should print the message saying that there was one file it was unable to read.)

Hope this helps!

**Comment by geblerj** [comment]
<img width="846" alt="File Explorer" src="https://user-images.githubusercontent.com/70666457/186302463-16b4bea9-f81a-43f8-9db0-e09f2f95dd60.png">
<img width="887" alt="Command Line" src="https://user-images.githubusercontent.com/70666457/186302480-d1bc0cdf-edaf-4a27-b336-2b3533c84987.png">


Images to demonstrate listdupes.py interpreting folder as file.

**Comment by Chris-Dobbins** [comment]
Thanks this is all really helpful. My macOS tester noticed that 0 byte file bug this morning as well, I accidentally introduced it in Beta 2 when I added lazy file reading as a feature. I put out a new beta version this afternoon that should fix the bug but I don't think my macOS tester has tried it yet. If you get a chance can you download [the v6 Beta 4 release](https://github.com/Chris-Dobbins/listdupes/releases/tag/v.6.0.0-beta.4) and confirm if the issue is fixed for you?

**Comment by geblerj** [comment]
@Chris-Dobbins no more errors.

**Comment by Chris-Dobbins** [comment]
@Chris-Dobbins Thanks for the quick work! I also opened a separate issue (#24) for the empty folder being counted as a file. There are times when treating folders as files makes sense, but that example definitely feels like bad program behavior to me too, so I'll work up a fix for that.

**Comment by geblerj** [comment]
@Chris-Dobbins yep no problem! Anything else you'd like me to test?

**Comment by Chris-Dobbins** [comment]
@geblerj Yeah I have one more thing, have you tried running listdupes with the optional `--progress` argument? I wanna make sure the method I'm using to animate the progress counter works in Windows. No need for in-depth testing of it right now, I'm going to be updating that code shortly, but it would be good to have a baseline. 

To test it I'd recommend using a folder with either a ton of files or a few fairly large files (say 250+ MB), otherwise the counter will finish so quickly you won't get a chance to see it move.
The expected behavior with a few large files should be something like this:

https://user-images.githubusercontent.com/107791888/186469084-86d6d2d6-8a44-46cb-bbf8-e6defa3eba55.mov

**Comment by geblerj** [comment]
Yeah I'll take a look at it

**Comment by geblerj** [comment]
Yep that works too

**Comment by Chris-Dobbins** [comment]
Fantastic! I'm really encouraged to see things working so well on Windows. When I opened this issue I figured it was gonna be a real grind. I think this is plenty of testing for now. I'm guessing there will be a few more betas and a few more weeks before v6.0.0 starts looking ready for an official release. I don't think any of those betas are like to cause Windows specific issues though. 

Once the betas are done and I've got a release candidate for v6 I'll drop you a note here, if you have time around then it'd be great to have you do a few final tests before we release it.

**Comment by geblerj** [comment]
Sounds good!

I should mention that when I tried running it on some of my files, I'm getting `TypeError: '<' not supported between instances of 'NoneType' and 'str'`. I'm going to do some digging to try and see what's causing it.

**Comment by Chris-Dobbins** [comment]
Ooooh that's an interesting bug, I haven't had any other reports of that. Feel free to open an issue for it with the traceback and whatever other info you've got, we should definitely get to the bottom of that.

**Comment by geblerj** [comment]
K will do
